import Head from "next/head";
import cards from "../db.json";
import Card from "../components/Card";
import styled from "styled-components";
import useSWR from "swr";

export default function HomePage() {
  const { data: attractions, isLoading, error } = useSWR("./api/places");

  if (error) {
    return <h1>{error.message}</h1>;
  }

  return (
    <>
      <Head>
        <title>Tourio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledList>
        {isLoading ? (
          <h2>Loading...</h2>
        ) : (
          attractions.map((attraction) => (
            <li key={attraction.id}>
              <Card
                name={attraction.name}
                location={attraction.location}
                image={attraction.image}
              />
            </li>
          ))
        )}
      </StyledList>
    </>
  );
}

const StyledList = styled.ul`
  display: flex;
  flex-direction: column;
  list-style: none;
  justify-content: center;
  align-items: center;
  gap: 10px;
  padding: 0;
  margin-top: 95px;
`;
