import Head from "next/head";
import cards from "../db.json";
import Card from "../components/Card";
import styled from "styled-components";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Tourio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledList>
        {cards.map((card) => (
          <li key={card.id}>
            <Card
              name={card.name}
              location={card.location}
              image={card.image}
            />
          </li>
        ))}
      </StyledList>
    </>
  );
}

const StyledList = styled.ul`
  display: flex;
  flex-direction: column;
  list-style: none;
  justify-content: center;
  align-items: center;
  gap: 10px;
  padding: 0;
  margin-top: 95px;
`;
